### ISSUE TITLE
Set up an OTP instance taking too long

### ISSUE THREAD

**Issue by kimnewzealand** [ropensci/opentripplanner#30] opened 2019-05-29 23:42 UTC
I have successfully created a graph object but it seems like there is a potential issue with setting up the OTP instance. See below error message.

` log <- otp_build_graph(otp = path_otp, dir = path_data, memory = 1) `
> Basic checks completed, building graph, this may take a few minutes
> Graph built

` otp_setup(otp = path_otp, dir = path_data)`
> 2019-05-30 11:05:41 OTP is loading and may take a while to be useable
> 2019-05-30 11:11:05 OTP is taking an unusually long time to load, releasing R to your control

## Trying the other alternative ports example
` otp_setup(otp = path_otp, dir = path_data, port = 8801, securePort = 8802)`
> 2019-05-30 11:11:06 OTP is loading and may take a while to be useable
> 2019-05-30 11:16:29 OTP is taking an unusually long time to load, releasing R to your control

**Comment by kimnewzealand** [comment] 2019-05-30 00:07
O this one does not appear to be an issue. I tried the memory=1 trick again and it worked so I will close

` otp_setup(otp = path_otp, dir = path_data,memory=1)`
> 2019-05-30 12:02:35 OTP is loading and may take a while to be useable
> Router http://localhost:8080/otp/routers/default exists
> 2019-05-30 12:05:47 OTP is ready to use Go to localhost:8080 in your browser to view the OTP

**Comment by mattdpalm** [comment] 2020-06-17 17:06
Hello,

I am encountering the same issue:

```
2020-06-15 01:35:22 OTP is loading and may take a while to be useable
2020-06-15 23:27:51 OTP is taking an unusually long time to load, releasing R to your control, OTP will continue in the background
```

 except the solution posted by Kiminnewzealand did not work for me. I tried:

```
log2 <- otp_setup(otp = path_otp, 
                  dir = path_data, router="MARTA 2019", memory=1)
```

and got the error:

`Assertion on 'memory' failed: Element 1 is not >= 500. `

**Comment by mem48** [comment] 2020-06-17 20:05
@mattdpalm are you using the demo data? What kind of computer are you using? Have you checked all the requirments in the prerequisites https://docs.ropensci.org/opentripplanner/articles/prerequisites.html

**Comment by mattdpalm** [comment] 2020-06-18 21:17
Malcolm, thank you. I managed to make it work with the demo data. But am
now trying to replicate with Atlanta Region GTFS and State of Georgia (USA)
OSM.
It's a laptop with 16 gig of ram, 64-bit, Windows 10, using the latest V8
of Java for 64 bit.

**Comment by mem48** [comment] 2020-06-19 08:44
The whole state of Georgia might be too big to fit in to 16GB of ram. I'd suggest trying a smaller are first like the biggest city to get a feel for how much RAM is needed. Remember to use the memory argument in otp_build_graph and otp_setup

**Comment by mem48** [comment] 2020-06-22 17:01
@mattdpalm I'm closing this issue as I don't think your problem is caused by anything wrong with the package.

**Closed as completed** 2020-06-22 17:01 UTC

**Comment by mattdpalm** [comment] 2020-06-30 15:31
Hi Malcom,

I reduced the OSM street file down to the Atlanta area.  The graph was
built--it's only 170 mb.  But I still receive the error code about it
taking too long to run. So the solution is memory=1?

Thank you

**Comment by mem48** [comment] 2020-06-30 15:36
Hi, @mattdpalm I think you are having the same problem at #65 so can you try the suggestions there and if that doesn't work post on that issue?
