### ISSUE TITLE
Can't create Graph.obj

### ISSUE THREAD

**Issue by StatistikVolker** [ropensci/opentripplanner#77] opened 2020-12-02 07:50 UTC
Thank you for the R Package opentripplannner.
Unfortunately it is for me not longer possible to create a userdefined Graph.obj.

I try this wiht fhr opentripplanner function otp_build_graph like this:

`city = "JENA"
optdir = "OTP3"
newdir <- file.path(getwd(), otpdir)
path_otp <- opentripplanner::otp_dl_jar(newdir, cache = FALSE)
log1 <- opentripplanner::otp_build_graph(otp = path_otp, dir = newdir,router = city,memory = 10240)`

The following Warning Message appears in the console:

`2020-12-02 08:22:56 Basic checks completed, building graph, this may take a few minutes
The graph will be saved to C:/Arbeitsordner/Jena/OTP_Jena/OTP3
2020-12-02 08:22:57 Graph built
Warning message:
In system(text, intern = TRUE) :
  running command 'java -Xmx10240M -jar "C:/Users/Volker/Documents/R/win-library/4.0/opentripplanner/jar/otp-1.4.0-shaded.jar" --build "C:/Arbeitsordner/Jena/OTP_Jena/OTP3/graphs/JENA"' had status 65535`

What does the Warning Message mean? What stands "status 65535" for?

Looking in the directory, no Graph.obj is in there (but it ist said it is build: "2020-12-02 08:22:57 Graph built")

This is why the next code chunk gives an error message:

`log2 <- opentripplanner::otp_setup(otp = path_otp, dir = newdir, router = city) #port = 8801, securePort = 8802,router = city)`

The Error Message is:

`Error in otp_checks(otp = otp, dir = dir, router = router, graph = TRUE) : 
  Assertion on 'paste0(dir, "/graphs/", router, "/Graph.obj")' failed: File does not exist: 'C:/Arbeitsordner/Jena/OTP_Jena/OTP3/graphs/JENA/Graph.obj'.`

I'm familiar with R but not with java.

Thank you for any hep!

V

**Comment by mem48** [comment] 2020-12-02 22:05
Please post the contents of the `log1` object it will contain the reason the graph did not build

**Comment by mem48** [comment] 2020-12-02 22:17
Also please comfrim you have checked all the common reasons for a failure listed in the documentation https://docs.ropensci.org/opentripplanner/articles/known_issues.html#reasons-for-graph-building-to-fail

**Comment by StatistikVolker** [comment] 2020-12-02 22:17
Thank you for your answer - I'' check yor link.

log1 contains this:

`> log1
 [1] "08:42:54.876 INFO (OTPServer.java:39) Wiring up and configuring server."                                                                                           
 [2] "08:42:54.881 INFO (GraphBuilder.java:165) Wiring up and configuring graph builder task."                                                                           
 [3] "08:42:54.884 INFO (GraphBuilder.java:171) Searching for graph builder input files in C:\\Arbeitsordner\\Jena\\OTP_Jena\\OTP3\\graphs\\JENA"                        
 [4] "08:42:54.884 INFO (OTPMain.java:203) File 'C:\\Arbeitsordner\\Jena\\OTP_Jena\\OTP3\\graphs\\JENA\\build-config.json' is not present. Using default configuration." 
 [5] "08:42:54.974 INFO (OTPMain.java:203) File 'C:\\Arbeitsordner\\Jena\\OTP_Jena\\OTP3\\graphs\\JENA\\router-config.json' is not present. Using default configuration."
 [6] "08:42:54.979 INFO (GraphBuilder.java:184) Summarizing GraphBuilderParameters"                                                                                      
 [7] "htmlAnnotations = false"                                                                                                                                           
 [8] "maxHtmlAnnotationsPerFile = 1000"                                                                                                                                  
 [9] "transit = true"                                                                                                                                                    
[10] "useTransfersTxt = false"                                                                                                                                           
[11] "parentStopLinking = false"                                                                                                                                         
[12] "stationTransfers = false"                                                                                                                                          
[13] "stopClusterMode = proximity"                                                                                                                                       
[14] "subwayAccessTime = 2.0"                                                                                                                                            
[15] "streets = true"                                                                                                                                                    
[16] "embedRouterConfig = true"                                                                                                                                          
[17] "areaVisibility = false"                                                                                                                                            
[18] "platformEntriesLinking = false"                                                                                                                                    
[19] "matchBusRoutesToStreets = false"                                                                                                                                   
[20] "fetchElevationUS = false"                                                                                                                                          
[21] "elevationBucket = null"                                                                                                                                            
[22] "elevationUnitMultiplier = 1.0"                                                                                                                                     
[23] "fareServiceFactory = DefaultFareServiceFactory"                                                                                                                    
[24] "customNamer = null"                                                                                                                                                
[25] "wayPropertySet = org.opentripplanner.graph_builder.module.osm.DefaultWayPropertySetSource@6a024a67"                                                                
[26] "staticBikeRental = false"                                                                                                                                          
[27] "staticParkAndRide = true"                                                                                                                                          
[28] "staticBikeParkAndRide = false"                                                                                                                                     
[29] "maxInterlineDistance = 200"                                                                                                                                        
[30] "pruningThresholdIslandWithoutStops = 40"                                                                                                                           
[31] "pruningThresholdIslandWithStops = 5"                                                                                                                               
[32] "banDiscouragedWalking = false"                                                                                                                                     
[33] "banDiscouragedBiking = false"                                                                                                                                      
[34] "maxTransferDistance = 2000.0"                                                                                                                                      
[35] "extraEdgesStopPlatformLink = false"                                                                                                                                
[36] ""                                                                                                                                                                  
[37] "08:42:54.979 ERROR (GraphBuilder.java:211) Found no input files from which to build a graph in C:\\Arbeitsordner\\Jena\\OTP_Jena\\OTP3\\graphs\\JENA"              
[38] "08:42:54.979 ERROR (OTPMain.java:112) An error occurred while building the graph."                                                                                 
attr(,"status")
[1] 65535`

**Comment by mem48** [comment] 2020-12-03 08:39
The problem is in the log

`"08:42:54.979 ERROR (GraphBuilder.java:211) Found no input files from which to build a graph in C:\\Arbeitsordner\\Jena\\OTP_Jena\\OTP3\\graphs\\JENA"`

**Comment by StatistikVolker** [comment] 2020-12-09 08:04
Dear Malcom,
thank you for your help - and sorry for the delay in answering: I was very busy with other things.
Of course you're right: Without input file - no graph.pbf is producable.
After that it was really easy - thanks!

But...

To produce my Inputfile, my workflow is:

I Download OSM Data from Geofabrik (https://download.geofabrik.de/europe/germany.html --> Column ".osm.pbf")
Download osmfilter and (in my case) osmconvert64 in the same folder
Then I start the console in Winwows (Windows + R --> cmd).
Change to the folder where the OSMfile is in.
convert the osm file (in this example it is "sachsen_latest.osm.pbf")
`osmconvert64 sachsen-latest.osm.pbf -o=sachsen.o5m`
Filter the streetnet
`osmfilter sachsen.o5m --keep="highway=" -o=sax_streetnet.o5m`
Convert back to pbf-Format:
`osmconvert64 sax_streetnet.o5m -o=sax_streetnet.pbf`
Copy sax_streetnet.pbf into my OTPname/praphs/city (in my case: OTPL/graphs/Leipzig)

I did it twice, once for "Thüringen", second for "Sachsen"
This works fine for "Thüringen", but not for "Sachsen".

Here I assume it is because f the OSM-file for Saxonia ("Sachsen").

The building of the graph for Saxonia lasts over an hour, results in an empty graph.obj-file.
in my log1 this line is repeated very often. (Instead of "0;8" there are other combinations as well.)

 [877] "06:09:24.009 WARN (OSMLevel.java:123) Could not determine floor number for layer 0;8, assumed to be ground-level."                                                                                                                 
 [878] "06:09:24.009 WARN (OSMDatabase.java:565) Could not infer floor number for layer called '0;8' at 736852708. Vertical movement will still be possible, but elevator cost might be incorrect. Consider an OSM level map."  

Thank you for any help!           

Stay healthy!

Greeting from Leipzig,

Volker

**Comment by mem48** [comment] 2020-12-09 22:05
The "Could not infer floor number for layer" are about OTP's support for elevators and are unlikly to cause the process to fail. I see many of these messages but they nexer cause the graph build to fail. The clue will be in the final few messages before the process fails.

**Comment by StatistikVolker** [comment] 2020-12-10 17:06
Dear Malcom,
that's right - the clue was in line 1011 of my log1.
`[1011] "Exception in thread \"main\" java.lang.OutOfMemoryError: GC overhead limit exceeded"`
With extenstion of the memory-option in `otp_build_graph` it worked fine!

Unfortunately only the first 1000 lines of `log1` where displayed on the screen by default.
I used then 
`log1[900:length(log1)] `
to display the last lines as well and found the message.

Is it possible to show the last 250 lines of the log1 by default, if `length(log1) > 1000`?

As I understand you,  only the last lines are relevant if the `graph.obj` is not build.

Thanks for your help, the really great package and stay helthy!

Volker

**Comment by mem48** [comment] 2020-12-11 15:19
you can show the top of any R object with `head()` and the  bottom with `tail()`

**Closed as completed by mem48** 2020-12-11 15:19 UTC
Labels: help wanted
